FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir streamlit==1.35.0 pandas==2.2.2 openpyxl==3.1.4 requests==2.32.2 plotly==5.22.0

COPY frontend/ ./frontend/

EXPOSE 8501
CMD ["streamlit", "run", "frontend/streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]
